image: docker:latest

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DOCKER_DRIVER: overlay2
  DATABASE_URL: 'mongodb://mongo/user_posts'
  # MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt


before_script:
  - docker login -u nefariusmag -p $DOKERHUB_PASS

build_job:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t nefariusmag/reddit:1.0 docker-monolith
    - docker push nefariusmag/reddit:1.0

# test_unit_job:
#   stage: test
#   services:
#     - mongo:latest
#   script:
#     - cd reddit
#     - ruby simpletest.rb

# test_integration_job:
#   stage: test
#   script:
#     - echo 'Testing 2'

deploy_dev_job:
  stage: review
  services:
    - docker:dind
  script:
    - docker pull nefariusmag/reddit:1.0
    - docker run --name reddit-dev -d -p 9292:9292 --network=host nefariusmag/reddit:1.0
  environment:
    name: dev
    url: http://35.204.192.31:9292
    on_stop: stop

stop:
  stage: review
  script: echo "Stop to dev"
  environment:
    name: dev
    action: stop
  when: manual

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: stop_branch
  only:
    - branches
  except:
    - master

stop_branch:
  stage: review
  script: echo "Stop to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    action: stop
  when: manual

staging:
  stage: stage
  when: manual
  only:
   - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
    on_stop: stop_stage

stop_stage:
  stage: stage
  script: echo "Stop to stage"
  environment:
    name: stage
    action: stop
  when: manual

production:
  stage: production
  when: manual
  only:
   - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
    on_stop: stop_prod

stop_prod:
  stage: production
  script: echo "Stop to production"
  environment:
    name: production
    action: stop
  when: manual
