image: docker:latest

stages:
  - build
  - test
  - review
  - stage
  - production

# variables:
  # DOCKER_DRIVER: overlay2
  # DATABASE_URL: 'mongodb://mongo/user_posts'
  # MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

before_script:
  - docker login -u nefariusmag -p $DOKERHUB_PASS

build_job:
  stage: build
  # services:
  #   - docker:dind
  script:
    - docker build -t nefariusmag/reddit:1.0 docker-monolith
    - docker push nefariusmag/reddit:1.0

# test_unit_job:
#   stage: test
#   services:
#     - mongo:latest
#   script:
#     - cd reddit
#     - ruby simpletest.rb

# test_integration_job:
#   stage: test
#   script:
#     - echo 'Testing 2'

deploy_dev_job:
  stage: review
  # services:
  #   - docker:dind
  script:
    - docker pull nefariusmag/reddit:1.0
    - if [ -n $(docker ps | grep reddit-dev) ]; then
          docker rm -f reddit-dev
      fi;
    - docker run --name reddit-dev -d -p 9294:9292 nefariusmag/reddit:1.0
  environment:
    name: dev
    url: http://35.204.192.31:9294
    on_stop: stop

stop:
  stage: review
  when: manual
  script:
    - if docker ps | grep reddit-dev; then
          docker rm -f reddit-dev
      fi;
  environment:
    name: dev
    action: stop

# branch review:
#   stage: review
#   script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
#   environment:
#     name: branch/$CI_COMMIT_REF_NAME
#     url: http://$CI_ENVIRONMENT_SLUG.example.com
#     on_stop: stop_branch
#   only:
#     - branches
#   except:
#     - master
#
# stop_branch:
#   stage: review
#   script: echo "Stop to $CI_ENVIRONMENT_SLUG"
#   environment:
#     name: branch/$CI_COMMIT_REF_NAME
#     action: stop
#   when: manual

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - docker pull nefariusmag/reddit:1.0
    - if docker ps | grep reddit-stage; then
          docker rm -f reddit-stage
      fi;
    - docker run --name reddit-stage -d -p 9293:9292 nefariusmag/reddit:1.0
  environment:
    name: stage
    url: http://35.204.192.31:9293
    on_stop: stop_stage

stop_stage:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - if docker ps | grep reddit-stage; then
          docker rm -f reddit-stage
      fi;
  environment:
    name: stage
    action: stop

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - docker pull nefariusmag/reddit:1.0
    - if docker ps | grep reddit; then
          docker rm -f reddit
      fi;
    - docker run --name reddit -d -p 9292:9292 nefariusmag/reddit:1.0
  environment:
    name: production
    url: http://35.204.192.31:9292
    on_stop: stop_prod

stop_prod:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - if docker ps | grep reddit; then
          docker rm -f reddit
      fi;
  environment:
    name: production
    action: stop
