version: '3.3'
services:

  post_db:
    env_file: .env
    image: mongo:${VERSION_DB}
    volumes:
      - post_db:/data/db
    ports:
      - 27017:27017
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    image: ${USER_NAME}/ui:${VERSION_APP}
    ports:
      - ${PORT_UI}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    env_file: .env
    image: ${USER_NAME}/post:${VERSION_APP}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
      front_net:
        aliases:
          - post

  comment:
    env_file: .env
    image: ${USER_NAME}/comment:${VERSION_APP}
    networks:
      back_net:
      front_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  back_net:
  front_net:
