version: '3.3'
services:

  post_db:
    env_file: .env
    image: mongo:${VERSION_DB}
    volumes:
      - post_db:/data/db
    ports:
      - 27017:27017
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    image: ${USER_NAME}/ui:${VERSION_APP}
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net

  post:
    env_file: .env
    image: ${USER_NAME}/post:${VERSION_APP}
    networks:
      back_net:
      front_net:
        aliases:
          - post

  comment:
    env_file: .env
    image: ${USER_NAME}/comment:${VERSION_APP}
    networks:
      back_net:
      front_net:
        aliases:
          - comment

  # prometheus:
  #   env_file: .env
  #   image: ${USER_NAME}/prometheus:${VERSION_APP}
  #   ports:
  #     - '9090:9090'
  #   networks:
  #     - back_net
  #     - front_net
  #
  # node-exporter:
  #   image: prom/node-exporter:${VERSION_APP}
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     - back_net
  #     - front_net
  #
  # mongodb-exporter:
  #   image: ${USER_NAME}/mongodb_exporter:${VERSION_APP}
  #   environment:
  #     MONGODB_URL: 'mongodb://post_db:27017'
  #   ports:
  #     - 9001:9001
  #   networks:
  #     - back_net
  #     - front_net
  #
  # blackbox-exporter:
  #   image: ${USER_NAME}/blackbox_exporter:${VERSION_APP}
  #   ports:
  #     - 9115:9115
  #   networks:
  #     - front_net
  #     - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
