version: '3'
services:

  fluentd:
    env_file: .env
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    env_file: .env
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    env_file: .env
    image: kibana
    ports:
      - "5601:5601"
