version: '3.5'
services:

  prometheus:
    env_file: .env
    image: ${USER_NAME}/prometheus:${VERSION_APP}
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - back_net
      - front_net

  # node-exporter:
  #   image: prom/node-exporter:v0.15.0
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     - back_net
  #     - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    deploy:
      mode: global
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

  mongodb-exporter:
    env_file: .env
    image: ${USER_NAME}/mongodb_exporter:${VERSION_APP}
    environment:
      MONGODB_URL: 'mongodb://post_db:27017'
    ports:
      - ${MONGODB_EXPORTER_URL}:9001
    networks:
      - back_net
      - front_net

  blackbox-exporter:
    env_file: .env
    image: ${USER_NAME}/blackbox_exporter:${VERSION_APP}
    ports:
      - ${BLACKBOX_PORT}:9115
    networks:
      - front_net
      - back_net

  cadvisor:
    env_file: .env
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '${CADVISOR_PORT}:8080'
    networks:
      - back_net
      - front_net

  grafana:
    env_file: .env
    image: grafana/grafana:5.0.0-beta4
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - back_net
      - front_net

  alertmanager:
    env_file: .env
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - ${ALTERMANAGER_PORT}:9093
    networks:
      - back_net
      - front_net

  zipkin:
    env_file: .env
    image: openzipkin/zipkin
    deploy:
      mode: global
    ports:
      - "${ZIPKIN_PORT}:9411"
    networks:
      back_net:
        aliases:
          - zipkin        
      front_net:
        aliases:
          - zipkin

volumes:
  grafana_data:

networks:
  back_net:
  front_net:
