version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${VERSION_DB}
    # container_name: mongo_db
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_APP}
    # container_name: ui
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - front_net
  post:
    env_file: .env
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_APP}
    # container_name: post
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_APP}
    # container_name: comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
