---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - image: nefariusmag/comment
        name: comment
        env:
        - name: COMMENT_DATABASE_HOST
          value: comment-db

---
apiVersion: v1
kind: Service
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  ports:
  - port: 9292
    protocol: TCP
    targetPort: 9292
    name: comment-1   
  - port: 4567
    protocol: TCP
    targetPort: 4567
    name: comment-2
  selector:
    app: reddit
    component: comment
